### PR TITLE
Setup Genomics Hub

### PR DESCRIPTION
**Pull request by petersudmant**
Creating a pull request for new IB134L Hub. 

Ref #648

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks for opening this up, @petersudmant! I've made a few changes:

1. Call this 'genomics' so it's a bit more generic, rather than something specific to one class. Maybe this can also be used by other classes in the space? Regardless, I generally prefer slightly more generic names. Hope this is ok?
2. I've set changed up a bit how packages get deployed, and explicitly installed pandas too (instead of depending on a version coming up from seaborn)
3. I've set up continuous deployment for this.
4. Filled in secrets, including Google Auth with Calnet ID. We'll move to using bcourses.berkeley.edu in a few days hopefully.

I've ported some of these changes to https://github.com/berkeley-dsep-infra/datahub/pull/1676, so it should automatically come in the next time someone makes a hub.

Does this all sound good to you?

**Comment by petersudmant** [comment]
Brilliant!

1) Sounds great
2) Super - there will be some updates I'll make from here, this is just a start
3) Great
4. Thank you - I couldn't figure out how to do this. 

It all sounds great ! thank you!

**Comment by yuvipanda** [comment]
@petersudmant awesome :) I had already pushed a bunch of my commits to this PR... If this all looks good to you, I'll merge this?

**Comment by petersudmant** [comment]
Yes please! THanks so much

**Comment by yuvipanda** [comment]
@petersudmant check out genomics.datahub.berkeley.edu!

**Comment by petersudmant** [comment]
AWESOME!!!! that's new since this a.m. 👍 

I'll work on updating this over next days. THANK YOU!

**Pull request merged**
