### PR TITLE
Bump to latest z2jh

### PR DESCRIPTION
**Pull request by yuvipanda**
Gets us the new autoscaler from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/502

### CODE REVIEW

**Comment by ryanlovett** [comment]
This failed on staging. The an awaiter pod tries to start but then gets to the Error state, after which a new pod is created. Their lifetime is about 2s but if I'm lucky with the timing I can get at the log with:
```
kubectl --namespace=staging log `kubectl --namespace=staging get pod | grep awaiter | awk '{print $1}'`
```
This produces:
```
2018/02/26 20:57:35 Can not parse API response as DaemonSet: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

From `get pod -o yaml`:
```
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"Job","namespace":"staging","name":"hook-image-awaiter-staging-147-1519678012","uid":"337b4879-1b36-11e8-bca5-000d3af9b008","apiVersion":"batch","resourceVersion":"18933918"}}
  creationTimestamp: 2018-02-26T21:01:09Z
  generateName: hook-image-awaiter-staging-147-1519678012-
  labels:
    controller-uid: 337b4879-1b36-11e8-bca5-000d3af9b008
    job-name: hook-image-awaiter-staging-147-1519678012
  name: hook-image-awaiter-staging-147-1519678012-4pxfn
  namespace: staging
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: hook-image-awaiter-staging-147-1519678012
    uid: 337b4879-1b36-11e8-bca5-000d3af9b008
  resourceVersion: "18933945"
  selfLink: /api/v1/namespaces/staging/pods/hook-image-awaiter-staging-147-1519678012-4pxfn
  uid: 2b9f216c-1b38-11e8-bca5-000d3af9b008
spec:
  containers:
  - command:
    - /image-awaiter
    - -ca-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -auth-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -api-server-address=https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)
    - -namespace=staging
    - -daemonset=hook-image-puller-staging-147-1519678012
    image: jupyterhub/k8s-image-awaiter:01eac78
    imagePullPolicy: IfNotPresent
    name: hook-image-awaiter-staging-147-1519678012
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-36kmm
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: k8s-pool1-38998895-2
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-36kmm
    secret:
      defaultMode: 420
      secretName: default-token-36kmm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-02-26T21:01:09Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-02-26T21:01:09Z
    message: 'containers with unready status: [hook-image-awaiter-staging-147-1519678012]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-02-26T21:01:09Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0697a8438a9eb45033759bb2e620d07d3f929c74a06611034abb0659b3e0ea3d
    image: jupyterhub/k8s-image-awaiter:01eac78
    imageID: docker-pullable://jupyterhub/k8s-image-awaiter@sha256:835ba6e34f9111ca58307e4d8228e465308e983989ebf72c2ab89b22030665fa
    lastState: {}
    name: hook-image-awaiter-staging-147-1519678012
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://0697a8438a9eb45033759bb2e620d07d3f929c74a06611034abb0659b3e0ea3d
        exitCode: 1
        finishedAt: 2018-02-26T21:01:11Z
        reason: Error
        startedAt: 2018-02-26T21:01:11Z
  hostIP: 10.240.0.5
  phase: Failed
  podIP: 10.244.1.209
  qosClass: BestEffort
  startTime: 2018-02-26T21:01:09Z
```

And `describe pod`:

```
Name:		hook-image-awaiter-staging-147-1519678012-h86fr
Namespace:	staging
Node:		k8s-pool1-38998895-2/10.240.0.5
Start Time:	Mon, 26 Feb 2018 21:02:24 +0000
Labels:		controller-uid=337b4879-1b36-11e8-bca5-000d3af9b008
		job-name=hook-image-awaiter-staging-147-1519678012
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"Job","namespace":"staging","name":"hook-image-awaiter-staging-147-1519678012","uid":"337b4879-1b36-11e8-bc...
Status:		Failed
IP:		10.244.1.238
Created By:	Job/hook-image-awaiter-staging-147-1519678012
Controlled By:	Job/hook-image-awaiter-staging-147-1519678012
Containers:
  hook-image-awaiter-staging-147-1519678012:
    Container ID:	docker://c2fc9b094d9fab7792246c0716a59340002940c08a6c935f41a474d68de75d26
    Image:		jupyterhub/k8s-image-awaiter:01eac78
    Image ID:		docker-pullable://jupyterhub/k8s-image-awaiter@sha256:835ba6e34f9111ca58307e4d8228e465308e983989ebf72c2ab89b22030665fa
    Port:		<none>
    Command:
      /image-awaiter
      -ca-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      -auth-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
      -api-server-address=https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)
      -namespace=staging
      -daemonset=hook-image-puller-staging-147-1519678012
    State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 26 Feb 2018 21:02:25 +0000
      Finished:		Mon, 26 Feb 2018 21:02:25 +0000
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-36kmm (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  default-token-36kmm:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-36kmm
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath							Type		Reason	Message
  ---------	--------	-----	----				-------------							--------	------	-------
  2s		2s		1	default-scheduler			Normal		Scheduled		Successfully assigned hook-image-awaiter-staging-147-1519678012-h86fr to k8s-pool1-38998895-2
  2s		2s		1	kubelet, k8s-pool1-38998895-2		Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-36kmm"
  1s		1s		1	kubelet, k8s-pool1-38998895-2	spec.containers{hook-image-awaiter-staging-147-1519678012}	Normal		Pulled	Container image "jupyterhub/k8s-image-awaiter:01eac78" already present on machine
  1s		1s		1	kubelet, k8s-pool1-38998895-2	spec.containers{hook-image-awaiter-staging-147-1519678012}	Normal		CreatedCreated container
  1s		1s		1	kubelet, k8s-pool1-38998895-2	spec.containers{hook-image-awaiter-staging-147-1519678012}	Normal		StartedStarted container
```

**Comment by ryanlovett** [comment]
`get ds -o yaml`
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    annotations:
      helm.sh/hook: pre-install,pre-upgrade
      helm.sh/hook-delete-policy: hook-succeeded,hook-failed
      helm.sh/hook-weight: "-10"
    creationTimestamp: 2018-02-26T20:47:02Z
    generation: 1
    labels:
      app: jupyterhub
      component: hook-image-puller-staging-147-1519678012
      heritage: Tiller
      hub.jupyter.org/deletable: "true"
      release: staging
    name: hook-image-puller-staging-147-1519678012
    namespace: staging
    resourceVersion: "18924829"
    selfLink: /apis/extensions/v1beta1/namespaces/staging/daemonsets/hook-image-puller-staging-147-1519678012
    uid: 32684f97-1b36-11e8-bca5-000d3af9b008
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jupyterhub
        component: hook-image-puller-staging-147-1519678012
        heritage: Tiller
        release: staging
    template:
      metadata:
        annotations:
          pod.alpha.kubernetes.io/init-containers: '[{"name":"image-pull-singleuser","image":"berkeleydsep/datahub-user:252b77c","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"image-pull-metadata-block","image":"jupyterhub/k8s-network-tools:81c2613","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"image-pull-geog187-image","image":"berkeleydsep/datahub-user-geog187:bb49103","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
          pod.beta.kubernetes.io/init-containers: '[{"name":"image-pull-singleuser","image":"berkeleydsep/datahub-user:252b77c","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"image-pull-metadata-block","image":"jupyterhub/k8s-network-tools:81c2613","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"},{"name":"image-pull-geog187-image","image":"berkeleydsep/datahub-user-geog187:bb49103","command":["/bin/sh","-c","echo
            \"Pulling complete\""],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
        creationTimestamp: null
        labels:
          app: jupyterhub
          component: hook-image-puller-staging-147-1519678012
          heritage: Tiller
          release: staging
      spec:
        automountServiceAccountToken: false
        containers:
        - image: gcr.io/google_containers/pause:3.0
          imagePullPolicy: IfNotPresent
          name: pause
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
          image: berkeleydsep/datahub-user:252b77c
          imagePullPolicy: IfNotPresent
          name: image-pull-singleuser
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
          image: jupyterhub/k8s-network-tools:81c2613
          imagePullPolicy: IfNotPresent
          name: image-pull-metadata-block
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
          image: berkeleydsep/datahub-user-geog187:bb49103
          imagePullPolicy: IfNotPresent
          name: image-pull-geog187-image
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 0
    templateGeneration: 1
    updateStrategy:
      type: OnDelete
  status:
    currentNumberScheduled: 4
    desiredNumberScheduled: 4
    numberAvailable: 4
    numberMisscheduled: 0
    numberReady: 4
    observedGeneration: 1
    updatedNumberScheduled: 4
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
`describe ds`

```
Name:		hook-image-puller-staging-147-1519678012
Selector:	app=jupyterhub,component=hook-image-puller-staging-147-1519678012,heritage=Tiller,release=staging
Node-Selector:	<none>
Labels:		app=jupyterhub
		component=hook-image-puller-staging-147-1519678012
		heritage=Tiller
		hub.jupyter.org/deletable=true
		release=staging
Annotations:	helm.sh/hook=pre-install,pre-upgrade
		helm.sh/hook-delete-policy=hook-succeeded,hook-failed
		helm.sh/hook-weight=-10
Desired Number of Nodes Scheduled: 4
Current Number of Nodes Scheduled: 4
Number of Nodes Scheduled with Up-to-date Pods: 4
Number of Nodes Scheduled with Available Pods: 4
Number of Nodes Misscheduled: 0
Pods Status:	4 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	app=jupyterhub
		component=hook-image-puller-staging-147-1519678012
		heritage=Tiller
		release=staging
  Init Containers:
   image-pull-singleuser:
    Image:	berkeleydsep/datahub-user:252b77c
    Port:	<none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    Environment:	<none>
    Mounts:		<none>
   image-pull-metadata-block:
    Image:	jupyterhub/k8s-network-tools:81c2613
    Port:	<none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    Environment:	<none>
    Mounts:		<none>
   image-pull-geog187-image:
    Image:	berkeleydsep/datahub-user-geog187:bb49103
    Port:	<none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    Environment:	<none>
    Mounts:		<none>
  Containers:
   pause:
    Image:		gcr.io/google_containers/pause:3.0
    Port:		<none>
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath	Type	Reason			Message
  ---------	--------	-----	----		-------------	--------------			-------
  18m		18m		1	daemon-set			Normal	SuccessfulCreate	Created pod: hook-image-puller-staging-147-1519678012-l9xjf
  18m		18m		1	daemon-set			Normal	SuccessfulCreate	Created pod: hook-image-puller-staging-147-1519678012-92fx6
  18m		18m		1	daemon-set			Normal	SuccessfulCreate	Created pod: hook-image-puller-staging-147-1519678012-s76c3
  18m		18m		1	daemon-set			Normal	SuccessfulCreate	Created pod: hook-image-puller-staging-147-1519678012-6wvpp
```

**Comment by ryanlovett** [comment]
This is with helm 2.5 and kubernetes 1.7.2. The z2jh pr says helm 1.7 is required. We ran into a [helm bug](https://github.com/kubernetes/helm/issues/3275) with helm 2.7+ so are somewhat reluctant to go back until it is fixed.

**Comment by yuvipanda** [comment]
@ryanlovett do you think I can convince you to upgrade to helm 2.8.1 and try again? If not, is ok!

**Comment by ryanlovett** [comment]
Yeah, I'm easy. I'll try the helm upgrade on its own first and if I run into the helm bug I'll either try some of the solutions/workarounds in that issue or revert.

**Comment by consideRatio** [comment]
@yuvipanda @ryanlovett 

Try upgrading to k8s 1.8+, I believe whats happening is that the master node that has the Kubernetes API sais it does not understand what the image-awaiter is asking it about. It will understand if it is version 1.8+ though.

__Extract from the PR__
> - It is no longer is responsible for creating and destroying a daemonset. It will simply wait for the deamonset's status to stabilize ([`desiredNumberScheduled == numberReady`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#daemonsetstatus-v1-apps)). This requires K8s 1.8+.

__Error message__
> `2018/02/26 20:57:35 Can not parse API response as DaemonSet: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}`

**Comment by consideRatio** [comment]
OH! I said helm 1.7+ was required but i meant helm 2.7+ =/

**Comment by consideRatio** [comment]
@ryanlovett everything will work without helm 2.7, but the objects created with hook enabled will not be automatically removed.

If you do not want to update, but still use the helm hook that allow upgrades to be made that will pull images before upgrading, you could delete them manually after by...

```
# manual cleanup of abandoned resources
kubectl delete all --selector hub.jupyter.org/deletable=true
```

**Comment by consideRatio** [comment]
@ryanlovett I'm curious to know if a k8s upgrade to 1.8+ solved the problems and if that was an option for your cluster - it would make me happy =D

**Comment by ryanlovett** [comment]
@consideRatio There's a commit in helm which will land in 2.8.2 that fixes a problem for us in 2.7-2.8.x. After we upgrade to that we can try the new chart. It will be much more difficult for us to upgrade kubernetes since we're in the middle of a semester with thousands of users and I don't completely trust the upgrade process. I'll keep you posted after we try the new chart though.

I may try on another cluster that's serving a much smaller course, but it is already running k8s 1.8.x.

**Comment by consideRatio** [comment]
@ryanlovett ah! Thanks for satisfying my curiosity! Wow... It feels so good for me to spend time working on things that I really think matter. I'm currently writing a proposal for national funding, I'm really hoping to be able to work full time on z2jh contributions and usage within the educational sector.

The work you do is creating ripples =) I'm excited!

**Comment by ryanlovett** [comment]
Yes, a better autoscaler will have a huge impact for us and everyone using z2jh. Thanks so much for working on it! :)

**Pull request merged**
