### PR TITLE
Add a dependency on OpenAI Gym for the ds102 environment.yml

### PR DESCRIPTION
**Pull request by Karl-Krauth**
added openai gym to the dependencies.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@Karl-Krauth heya! Thanks for opening this. Looks like the build failed for the change you added. Can you look at it? Thanks!

**Comment by Karl-Krauth** [comment]
Hmm strange. Ill take a look at it deeper later today but the error message isnt giving me great diagnostics on what might be wrong (I only added gym to requirements.txt)

**Comment by Karl-Krauth** [comment]
It seems that the issue is that `conda update -q conda` is somehow being trigerred in the deploy now and this results in setuptools being removed which causes a failure since conda depends on it. I'm not sure why adding a new package might cause this though.

**Comment by Karl-Krauth** [comment]
Ah I see it seems that I was trying to install gym via conda when I should have been trying to do it via pip. Hopefully the tests pass now :)

**Pull request closed without merging**
