### PR TITLE
Add JupyterBook to default 159 image

### PR DESCRIPTION
**Pull request by fperez**

### CODE REVIEW

**Comment by yuvipanda** [comment]
stat159 has its own image now - at https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/stat159/image. I'll add it there, hang on.

**Comment by fperez** [comment]
Ah, thanks, sorry about the confusion! I'll update my bookmark for where to go when making these small tweaks :)

**Comment by yuvipanda** [comment]
I've included your commits in https://github.com/berkeley-dsep-infra/datahub/pull/2274, will merge that when ready.

**Comment by yuvipanda** [comment]
@fperez yw! fwiw, since it has its own image, xeus and friends are available if needed :)

**Pull request closed without merging**
