### PR TITLE
Add lime and shap to requirements for DS102

### PR DESCRIPTION
**Pull request by rameshvs**
We're experimenting with LIME and SHAP for ML explainability in DS102 and would like these packages installed. They seem to install cleanly on datahub, so I don't anticipate any issues coming up (like we had with theano earlier in the semester).

### CODE REVIEW

**Comment by rameshvs** [comment]
@yuvipanda

**Comment by yuvipanda** [comment]
Thanks, @rameshvs!

**Comment by rameshvs** [comment]
@yuvipanda when I try importing the packages, it doesn't seem like they've been installed (on data102.datahub.berkeley.edu, with a fresh server that just started up a few minutes ago). Do you know if I should expect to see them? Thanks!

**Comment by yuvipanda** [comment]
@rameshvs it needed https://github.com/berkeley-dsep-infra/datahub/pull/2286 to be merged, which I have just done - sorry about the delay. Should be available now.

**Pull request merged**
