### PR TITLE
Adding admins to prod.

### PR DESCRIPTION
**Pull request by gunjanbaid**
@yuvipanda @vinitra

### CODE REVIEW

**Comment by yuvipanda** [comment]
cool! Am merging this now

**Comment by yuvipanda** [comment]
You can see deployment progress on all merges at https://travis-ci.org/berkeley-dsep-infra/datahub/builds

**Comment by yuvipanda** [comment]
Forgot to ping here, but all of these folks should now be admins on datahub.yuvi.in. @vinitra @gunjanbaid can you verify?

But yeah, this is the entire deployment process :)

**Comment by gunjanbaid** [comment]
@yuvipanda I have admin access on prod too!

**Comment by vinitra** [comment]
Can comfirm!

**Pull request merged**
