### PR TITLE
Added pysal to requirements.txt

### PR DESCRIPTION
**Pull request by samyag1**
Added the pysal python module for David O'Sullivan's geog88 connector course

### CODE REVIEW

**Comment by ryanlovett** [comment]
Hi @samyag1, pysal was pulled in yesterday. Is it not available in your singleuser server?

If your server has persisted for some time, you may need to stop and start your server to pick up the latest docker image.

**Comment by samyag1** [comment]
Hi Ryan,

Sorry for the confusion! I meant to make that last pull request to the prod
branch, as I tested the staging branch and it worked fine this morning.
Should I submit another pull request? That's what I understood the process
to be from the readme on the github page.

Thanks,
Sam

**Comment by ryanlovett** [comment]
Hi Sam,

Normally that would be the correct procedure but pysal was already integrated into staging and prod last night. Every now and then multiple people do overlapping PRs and merges, and patches get lost. Before you to a commit or push to staging, make sure to pull from staging in the event there are new commits from elsewhere. I should add this to the docs.

**Comment by samyag1** [comment]
Ah, I see. Will do! And thanks for the education...

**Pull request closed without merging**
