### PR TITLE
new w261 cluster

### PR DESCRIPTION
**Pull request by jameswinegar**

### CODE REVIEW

**Comment by jameswinegar** [comment]
@yuvipanda having issues with the timeout for new deployments as noted here. https://github.com/yuvipanda/hubploy/issues/17.

Thoughts?

FYI I don't have delete cluster privileges, can you run the following? `gcloud container clusters delete w261-testing`

```
$ kubectl --namespace=w261-staging get svc
NAME              TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
hub               ClusterIP      10.0.26.246   <none>        8081/TCP                     2m57s
kube-lego-nginx   ClusterIP      10.0.24.167   <none>        8080/TCP                     2m38s
proxy-api         ClusterIP      10.0.21.87    <none>        8001/TCP                     2m57s
proxy-http        ClusterIP      10.0.27.112   <none>        8000/TCP                     2m57s
proxy-public      LoadBalancer   10.0.28.31    <pending>     80:30209/TCP,443:30655/TCP   2m57s
```

```
$ hubploy deploy w261 hub staging
Activated service account credentials for: [hubploy@ucb-datahub-2018.iam.gserviceaccount.com]
Fetching cluster endpoint and auth data.
kubeconfig entry generated for fall-2019.
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading jupyterhub from repo https://jupyterhub.github.io/helm-chart
Deleting outdated charts
Release "w261-staging" does not exist. Installing it now.
Error: release w261-staging failed: timed out waiting for the condition
Traceback (most recent call last):
  File "/home/jameswine/.local/share/virtualenvs/datahub-nG9xbyzb/bin/hubploy", line 10, in <module>
    sys.exit(main())
  File "/home/jameswine/.local/share/virtualenvs/datahub-nG9xbyzb/lib/python3.7/site-packages/hubploy/__main__.py", line 65, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version)
  File "/home/jameswine/.local/share/virtualenvs/datahub-nG9xbyzb/lib/python3.7/site-packages/hubploy/helm.py", line 128, in deploy
    version
  File "/home/jameswine/.local/share/virtualenvs/datahub-nG9xbyzb/lib/python3.7/site-packages/hubploy/helm.py", line 58, in helm_upgrade
    subprocess.check_call(cmd)
  File "/home/jameswine/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'w261-staging', 'w261-staging', 'hub', '-f', 'deployments/w261/config/common.yaml', '-f', 'deployments/w261/config/staging.yaml', '-f', 'deployments/w261/secrets/staging.yaml', '--set', 'jupyterhub.singleuser.image.tag=025f383', '--set', 'jupyterhub.singleuser.image.name=gcr.io/ucb-datahub-2018/w261-user-image']' returned non-zero exit status 1.
```
```
$ kubectl config current-context
gke_ucb-datahub-2018_us-central1_fall-2019
```

**Comment by yuvipanda** [comment]
@jameswinegar I don't think #17 is related. It is related to the public IP pinning in https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/w261/config/prod.yaml#L7 and https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/w261/config/staging.yaml#L4. Those IPs are no longer reserved, so that's problematic. Need to get that out and that should work.

If we use a new project, we'd also need to use a different filesystem. I think that's reasonably easy though...

#805 has a little more info on new cluster creation, although for testing I don't think most of that matters.

**Comment by yuvipanda** [comment]
I made a new project, and am creating a cluster with:

```bash
   gcloud container clusters create \
        --enable-ip-alias \
        --enable-autoscaling \
        --max-nodes=10 --min-nodes=1 --num-nodes=1 \
        --region=us-central1 --node-locations=us-central1-b \
        --image-type=ubuntu \
        --disk-size=100 --disk-type=pd-standard \
        --machine-type=n1-highmem-4 \
        --cluster-version latest \
        --no-enable-autoupgrade \
        w261-2019
```

**Comment by yuvipanda** [comment]
I also created a 1 TB NFS cloud fileshare

**Comment by yuvipanda** [comment]
I created two new service accounts:

1. hubploy - with 'Google Kubernetes Cluster Viewer' and 'Kubernetes Engine Developer' roles
2. gcr-readwrite - with 'Storage Admin' role

**Comment by yuvipanda** [comment]
I've set up helm with helm 2.12 (since that's the helm version we use elsewhere in CI right now) on the new cluster

**Comment by yuvipanda** [comment]
CircleCI should now be building w261 image too

**Comment by yuvipanda** [comment]
Now running a local image build + push

**Pull request merged**
