### PR TITLE
Add IRKernel for geog187

### PR DESCRIPTION
**Pull request by xrwang**
Hi there!

I'm GSI-ing for [Geography 187 in Spring 2018](http://geography.berkeley.edu/wp-content/uploads/2016/07/geog187spring-2016.pdf). We plan on using notebooks for the labs, and have two labs that require using R and a few R packages. 

LMK what you think. Thank you !

### CODE REVIEW

**Comment by gunjanbaid** [comment]
@yuvipanda @ryanlovett

**Comment by ryanlovett** [comment]
@papajohn How do you feel about there being a second kernel?

Wrt this PR, the libraries should be specified reproducibly with versioning.

**Comment by papajohn** [comment]
Seems like running a second hub might be better, so people on datahub don’t
have to learn to select the right kernel.

**Comment by yuvipanda** [comment]
I think this should be a separate image that inherits from the datahub image + adds R Kernel. And then we should whitelist the students who get it.

**Comment by yuvipanda** [comment]
data8 students should never see a non-python3 kernel. I think that's a good rule to follow generally.

**Comment by ryanlovett** [comment]
Just following up, we are going to implement this by having datahub start up a different single user image for geog187 students. We'll associate the login names of course students with this augmented image on the hub side.

@xrwang When in Spring '18 will the R-based labs be held?

**Comment by xrwang** [comment]
@ryanlovett labs will start week of 1/22/18 in spring semester (second week of spring semester). 

How/who should I send the list of course student login names to?

Also LMK if there's anything else you need from my end for implementation + augmented image. Thanks so much!

**Comment by ryanlovett** [comment]
@xrwang When will the two R-based labs be held?

I should be able to acquire the course roster from the Student Information System, but I'll confirm the list with you.

**Comment by xrwang** [comment]
@ryanlovett apologies, I misspoke about the 2 labs. There's actually 5. 

- There will be **5 lab homework assignments** in R for the semester.
- There are accompanying lab sessions happening Tuesday and Thursday of each week where students can work on their assignments with a GSI present. 
- The accompanying lab sessions begin the second week of the semester (week of 1/22)  and are held every week until the end of the semester.

Thank you!

**Comment by ryanlovett** [comment]
Working on part of this in #178.

**Comment by ryanlovett** [comment]
Fixed, in part by #178 - #183.

@xrwang, can you please email me your berkeley.edu email address so that I can enable the image for you? I was able to fetch the student addresses from the SIS today.

**Pull request closed without merging**
