### PR TITLE
Add PH142 installations

### PR DESCRIPTION
**Pull request by corinne-riddell**
I didn't include the `ref=` argument in `install_github`, though not sure if i need to...

### CODE REVIEW

**Comment by yuvipanda** [comment]
w00t, thanks for taking this on, @corinne-riddell! 

You do need to specify 'ref', and point it to the current version. This ensures you get a consistent version throughout the semester - otherwise they might get upgraded as a surprise to you randomly!

For stuff in cran, the ref is usually the version number. For example, for fGarch (https://cran.r-project.org/web/packages/fGarch/index.html), the version number right now is '3042.83.1' so that should be the ref. You can verify this by going to https://github.com/cran/fGarch/, clicking 'releases' and making sure an entry exists for that version.

For patchwork, from https://github.com/thomasp85/patchwork it looks like they haven't made a release yet. In that case, my recommendation is to:

1. Click the 'Commits' link (which lists all the commits to this repo)
2. Get the full commit hash of the latest commit by pressing the clipboard icon next to it. This should put something like '36b4918777c25393df605a4959a4c9690d2af186' in your clipboard. This is the git commit hash, and will refer to this particular version consistently
3. Use that as a ref.

Hope this is helpful!

And welcome to directly contributing to making changes for your teaching environment!

**Comment by corinne-riddell** [comment]
Thanks for the pro tips @yuvipanda! This commit now includes refs 😄

**Comment by yuvipanda** [comment]
Thanks, @corinne-riddell!

It looks like our GitHub API limit is causing problems :( I'll take a look hopefully later today.

**Comment by ryanlovett** [comment]
@yuvipanda The [class_libs_install_version](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/r/image/class-libs.R#L15) function avoids github. That function is appropriate to use if the version of the library you want to install is in the configured CRAN mirror (our rocker-based image uses https://cran.microsoft.com/snapshot/2019-07-05/).

**Comment by yuvipanda** [comment]
@felder is now pushing this forward with the additional GitHub Auth fixes in #1046. 

Thanks for making the PR, @corinne-riddell! I am hopefull the GitHub Auth fixes will make PRs like this easier in the future.

**Pull request closed without merging**
