### PR TITLE
Maptools

### PR DESCRIPTION
**Pull request by xrwang**
@ryanlovett adding `maptools` package to the geog187 image.
Thank you : )

### CODE REVIEW

**Comment by henchc** [comment]
thanks @xrwang can you watch the build in staging [here](https://travis-ci.org/berkeley-dsep-infra/datahub/builds) then once it's built and deployed check on the [staging site](staging.datahub.berkeley.edu) that it works correctly? Thanks!

**Comment by ryanlovett** [comment]
@henchc @xrwang when the helm chart was updated, in part to use the new image puller, i had to temporarily disable part of the secondary image stuff. I'll probably need to update the mechanism and will take a look so soon. Sorry for the inconvenience!

**Comment by xrwang** [comment]
thanks @henchc @ryanlovett ! For now, on [staging](staging.datahub.berkeley.edu) I get a continuously loading state, which sounds like it's likely related to secondary image disabling.

**Comment by henchc** [comment]
sorry @xrwang i think @ryanlovett is still fixing some things, we'll let you know when it's up.

**Comment by xrwang** [comment]
\o/ library(maptools) is working on staging. Thanks so much!

**Comment by ryanlovett** [comment]
@xrwang I'm still making changes but I'm glad staging is working for you. A service we rely on for our build infrastructure is having trouble right now which will unfortunately delay deployment to production.

**Comment by ryanlovett** [comment]
@xrwang This should be on prod by tonight. I'm waiting until after Data8 labs today.

**Pull request merged**
