### PR TITLE
 Updated admins for sp18

### PR DESCRIPTION
**Pull request by AdeelCheema**

### CODE REVIEW

**Comment by ryanlovett** [comment]
@AdeelCheema do you want to merge this? Its okay to merge your own PRs if you don't need any feedback on them. I think you need to accept a repo invite though -- I can resend if needed.

**Comment by AdeelCheema** [comment]
@ryanlovett Sounds good, thank you! I just accepted the invite and will merge this in.

**Comment by AdeelCheema** [comment]
Actually, looks like I don't have write access, is there anything else that needs to be done besides accepting the invite?

**Comment by ryanlovett** [comment]
@AdeelCheema I've just set you to be an admin on this repo so you should be able to merge.

**Pull request merged**
