### PR TITLE
add networkx (dep decorator) and bokeh for modules

### PR DESCRIPTION
**Pull request by henchc**

### CODE REVIEW

**Comment by yuvipanda** [comment]
@henchc I've added you as a collaborator. can you confirm then merge?

**Comment by henchc** [comment]
done, thanks!

**Comment by yuvipanda** [comment]
@henchc now you need to verify this works on on staging.datahub.berkeley.edu, and then make a PR to 'prod' and merge that too.

**Comment by yuvipanda** [comment]
@henchc see https://github.com/berkeley-dsep-infra/datahub#procedure

**Comment by yuvipanda** [comment]
This also broke deploy on Travis. I've verified it works after doing a rebuild (just the 'restart build' button on Travis). Pushing to prod now.

**Pull request merged**
